name: TFLite
on: workflow_dispatch
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Build
        uses: ./tflite

      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: tflite
          path: public/tflite
